dream89_app_homepage:
    pattern:  /
    defaults: { _controller: dream89AppBundle:Default:index }

dream89_app_hello:
    pattern:  /hello
    defaults: { _controller: dream89.hello.controller:indexAction }
