app_homepage:
    pattern:  /
    defaults: { _controller: dream89AppBundle:Default:index }

app_download:
    pattern:  /download
    defaults: { _controller: dream89AppBundle:Default:download }

app_hello:
    pattern:  /hello
    defaults: { _controller: dream89.hello.controller:indexAction }
