parameters:
    dream89.controller.hello.class: dream89\AppBundle\Controller\HelloController

services:
    dream89.hello.controller:
        class:     "%dream89.controller.hello.class%"
        arguments: ["@templating"]