parameters:
#    dream89_app.example.class: dream89\AppBundle\Example

services:
#    dream89_app.example:
#        class: %dream89_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
